### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by JAntonioCoder** [SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-JAntonioCoder#1]
[Infografia__Topicos Avanzados.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-JAntonioCoder/files/14528171/Infografia__Topicos.Avanzados.pdf)

**Comment by Kim-Mendoza3** [comment]
Calificacion 18

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
